<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/ones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **how to create tensor with elements are one in tensorflow**

In [7]:
import tensorflow as tf

In [3]:
con=tf.ones(shape=(2,3),dtype="int32")
con

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [4]:
one_3dt=tf.ones(shape=(2,3,4),dtype="float32")
one_3dt

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

# **tf**.**ones_like**()
# create a tensor of all ones that has the same shape as the input

In [5]:
con_2dt=tf.constant([[1,2,3],[2,3,4]])
con_2dt

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4]], dtype=int32)>

In [7]:
v=tf.ones_like(con_2dt,dtype="float32")
v

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [8]:
VAR=tf.Variable([[2,3,4],[3,4,5]])
VAR

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5]], dtype=int32)>

In [9]:
con=tf.ones_like(VAR,tf.int32)
con

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

# **tf.ones_initializer()**
initializer that generates tensors initialized to 1


In [5]:
def ones_variable(shape,dtype,initializer):
  return tf.Variable(initializer(shape=shape,dtype=dtype))

In [8]:
ones_variable((2,2),tf.int32,tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [9]:
ones_variable((2,2,3),tf.int32,tf.ones_initializer())

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)>