<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/sparse_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Sparse** **tensor**

In [4]:
import tensorflow as tf

# **create** **tensorflow** **sparse** **tensor**

In [5]:
st1=tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])
st1

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))

In [7]:
print(st1)

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))


## **# create sparse tensor from dense**

In [9]:
import numpy as np

In [12]:
np_array=np.array([[1,0,0,0],
                  [0,0,1,0],
                  [0,1,0,0],
                  [0,1,0,0]])
np_array

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])

In [15]:
st2_fd=tf.sparse.from_dense(np_array)

In [16]:
print(st2_fd)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]
 [2 1]
 [3 1]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 1 1 1], shape=(4,), dtype=int64), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


# **extract te values ,indices & shape of sparse tensor**

In [17]:
st2_fd.values.numpy().tolist()

[1, 1, 1, 1]

In [18]:
st2_fd.indices.numpy().tolist()

[[0, 0], [1, 2], [2, 1], [3, 1]]

In [20]:
st2_fd.dense_shape.numpy()

array([4, 4])

# **# sparse tensor to Dense**

In [23]:
dt_fst=tf.sparse.to_dense(st2_fd)
dt_fst

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0]])>

# **mathematical operation on sparse tensor**

In [25]:
st_add=tf.sparse.add(st2_fd,st2_fd)
st_add

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]
 [2 1]
 [3 1]], shape=(4, 2), dtype=int64), values=tf.Tensor([2 2 2 2], shape=(4,), dtype=int64), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))

In [26]:
tf.sparse.to_dense(st_add).numpy()

array([[2, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 2, 0, 0],
       [0, 2, 0, 0]])