<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/tf.math_module_division.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **tf.sqrt()**

In [11]:
import tensorflow as tf
import numpy as np

# **Square Root of Scaler**

In [13]:
a=9.0

In [14]:
tf.sqrt(a)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

# **Square Root of List/Tuple**

In [17]:
l1=[4.0,9.0,16.0]
tf.sqrt(l1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [18]:
t1=(4.0,9.0,16.0)
tf.sqrt(t1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

# **square Root of Numpy Array**

In [19]:
npa1=np.array([4,9,16],dtype=np.float32)
tf.sqrt(npa1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [20]:
npa1.dtype

dtype('float32')

In [21]:
y=np.ones(6).reshape(2,1,3,1)*4
y

array([[[[4.],
         [4.],
         [4.]]],


       [[[4.],
         [4.],
         [4.]]]])

In [22]:
tf.sqrt(y)

<tf.Tensor: shape=(2, 1, 3, 1), dtype=float64, numpy=
array([[[[2.],
         [2.],
         [2.]]],


       [[[2.],
         [2.],
         [2.]]]])>

# **Square Root of Tensor**

In [23]:
tf.sqrt(tf.convert_to_tensor(4,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [24]:
tf.sqrt(tf.convert_to_tensor([4,9,16],dtype=tf.float32))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

# **Square Root of constant tensor**

In [27]:
tf_ct1=tf.constant([4,9,16],dtype="float32")
tf_ct1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 4.,  9., 16.], dtype=float32)>

# **Square Root of Variable tensor**

In [28]:
tf_vr1=tf.Variable([4,9,16],dtype="float32")
tf_vr1

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 4.,  9., 16.], dtype=float32)>