<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/tf.math_module_power.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tf.pow()

In [2]:
import tensorflow as tf
import numpy as np

# **Power of Scaler**

In [3]:
a=4
b=2
tf.pow(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=16>

# **power of numpy array**

In [5]:
npa1=np.array([2,3,4],dtype="float32")
tf.pow(npa1,2)


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 4.,  9., 16.], dtype=float32)>

In [6]:
npa1=np.array([2,3,4])
npa2=np.array([1,2,3])
tf.pow(npa1,npa2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([ 2,  9, 64])>

In [7]:
y=np.ones(6).reshape(2,1,3,1)*4
y

array([[[[4.],
         [4.],
         [4.]]],


       [[[4.],
         [4.],
         [4.]]]])

In [8]:
tf.pow(y,2)

<tf.Tensor: shape=(2, 1, 3, 1), dtype=float64, numpy=
array([[[[16.],
         [16.],
         [16.]]],


       [[[16.],
         [16.],
         [16.]]]])>

# **Power of Tensor**

In [9]:
tf.pow(tf.convert_to_tensor([4,5,6],dtype="float"),2)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([16., 25., 36.], dtype=float32)>

# **Power of TF Constant Tensor**

In [10]:
tf_ct1=tf.constant([4,5,6,7],dtype="float")
tf.pow(tf_ct1,2)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([16., 25., 36., 49.], dtype=float32)>

# **Power of TF Variable Tensor**

In [5]:
tf_vr1=tf.Variable([64,9,4,255])
tf_vr2=tf.Variable([2,3,2,5])
tf.pow(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([     4096,       729,        16, 167118079], dtype=int32)>

In [4]:
tf_vr1=tf.Variable([4,9,4,5])
tf.pow(tf_vr1,2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([16, 81, 16, 25], dtype=int32)>

In [6]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=tf.Variable([3])
tf.pow(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  8, 27, 64], dtype=int32)>