<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/tf.math_module_multiply.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tf.multiply()**

In [16]:
import tensorflow as tf
import numpy as np

# **scaler multiply**

In [17]:
a=10
b=20
tf.multiply(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=200>

# **multiply 2 list/tuple**

In [18]:
l1=[1,2,3,4]
l2=[2,3,4,5]
tf.multiply(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  6, 12, 20], dtype=int32)>

In [19]:
t1=(1,2,3,4)
t2=(2,3,4,5)
tf.multiply(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  6, 12, 20], dtype=int32)>

# **multiply list/tuple with scaler**

In [20]:
l1=[1,2,3,4]
l2=[2]
tf.multiply(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [21]:
t2=(2,3,4,5)
t1=(5)
tf.multiply(t2,t1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 15, 20, 25], dtype=int32)>

# **multiply numpy array**

In [22]:
npa1=np.array([1,2,3,4])
npa2=np.array([2,3,4,5])
tf.multiply(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 2,  6, 12, 20])>

# **multiply numpy array with different size**

In [23]:
npa1=np.array([1,3,4,5])
npa2=np.array([3])
tf.multiply(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 3,  9, 12, 15])>

# **multiply 2 tensor constant**

In [24]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=tf.constant([5,5,6,7])
tf.multiply(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 10, 18, 28], dtype=int32)>

## **multiply** **constant**  **tensor** **with** **different** **shape**

In [27]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=tf.constant([5])
tf.multiply(tf_ct1,tf_ct2)
#

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 10, 15, 20], dtype=int32)>

# **multiply 2 variable tensor**

In [29]:
vr1=tf.Variable([1,2,3,4])
vr2=tf.Variable([5,5,6,7])
tf.multiply(vr1,vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 10, 18, 28], dtype=int32)>

## **multiply** **variable**  **tensor** **with** **different** **shape**

In [28]:
vr1=tf.Variable([1,2,3,4])
vr2=tf.Variable([3])
tf.multiply(vr1,vr2)
#

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  6,  9, 12], dtype=int32)>