<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/tf.math_module_subtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tf.subtract**

In [1]:
import tensorflow as tf
import numpy as np

# **Scaler subtract**

In [4]:
a=19
b=34
tf.subtract(b,a)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

# **subtract 2 list**

In [5]:
l1=[1,2,3,4]
l2=[5,6,8,8]
tf.subtract(l2,l1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 4, 5, 4], dtype=int32)>

# **subtarct 2 tuple**

In [7]:
t1=(1,2,3,4)
t2=(5,6,7,8)
tf.subtract(t2,t1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 4, 4, 4], dtype=int32)>

# **subtract of list/tuple with scaler**

In [8]:
a=12
b=[20,30,40]
tf.subtract(b,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 8, 18, 28], dtype=int32)>

# subtract of 2 list/tuple with different **size**

In [9]:
l1=[12,22,32,42]
l2=[5]
tf.subtract(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7, 17, 27, 37], dtype=int32)>

# **subtract 2 numpy array**

In [10]:
npa1=np.array([1,2,3,4])
npa2=np.array([2,3,4,5])
tf.subtract(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([-1, -1, -1, -1])>

# **subtract numpy array with scaler**

In [11]:
npa1=np.array([1,2,3,4])
npa2=np.array([2])
tf.subtract(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([-1,  0,  1,  2])>

# **subtract 2 tf constant tensor**

In [12]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=tf.constant([2,3,4,5])
tf.subtract(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -1, -1, -1], dtype=int32)>

# **subtract tf constant tensor with scaler**

In [13]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=tf.constant([2])
tf.subtract(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1,  0,  1,  2], dtype=int32)>

# **subtract 2 tf variable**

In [14]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=tf.Variable([2,3,4,5])
tf.subtract(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -1, -1, -1], dtype=int32)>

# **subtract tf variable with scaler**

In [15]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=tf.Variable([2])
tf.subtract(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1,  0,  1,  2], dtype=int32)>