<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/tf.math_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tensorflow math.module**

**tf**.**add**():Do element wise addition

In [34]:
import tensorflow as tf
import numpy as np

# **Scaler Adding**

In [36]:
a=10
b=19


In [37]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=29>

# **Add 2 list**

In [38]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
tf.add(l1,l2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 7,  9, 11, 13, 15], dtype=int32)>

# **Add 2 Tuple**

In [39]:
t1=(1,2,3,4)
t2=(2,3,4,5)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 5, 7, 9], dtype=int32)>

# **Add list\tuple with scalar**

In [40]:
tf.add(l1,a)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 12, 13, 14, 15], dtype=int32)>

In [41]:
tf.add(t1,b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([20, 21, 22, 23], dtype=int32)>

# **Addition of 2 List/Tuple with different Size**


In [42]:
l1=[1,2,3,4]
l2=[1,2]
tf.add(l1,l2)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4] vs. [2] [Op:AddV2] name: 

# **Add 2 Numpy Array**

In [44]:
npa1=np.array([1,2,3,4])
npa2=np.array([4,5,6,8])
tf.add(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([ 5,  7,  9, 12])>

# **Add Numpy array with Scaler**

In [45]:
tf.add(a,npa1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

# **Add Numpy array with single element np array**

In [46]:
npa1=np.array([1,2,3,4])
npa2=np.array([4])
tf.add(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 6, 7, 8])>

# **Add  2 TF Constant Tensor**

In [49]:
con=tf.constant([[1,2],[3,4]])
con1=tf.constant([[4,5],[6,7]])
tf.add(con,con1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  7],
       [ 9, 11]], dtype=int32)>

# **Add  2 TF Constant Tensor with scaler**

In [50]:
con=tf.constant([1,2,3,4])
a=89
tf.add(con,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([90, 91, 92, 93], dtype=int32)>

# **Add  2 TF Variable Tensor**

In [51]:
vr=tf.Variable([2,3,4,5])
vr1=tf.Variable([4,5,6,7])
tf.add(vr,vr1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

# **Add  2 TF Variable Tensor with Scaler**

In [52]:
vr=tf.Variable([9,8,7])
a=12
tf.add(vr,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([21, 20, 19], dtype=int32)>

# **Add  2 Numpy array with different shape**

In [54]:
x=np.ones(6).reshape(1,2,1,3)
x

array([[[[1., 1., 1.]],

        [[1., 1., 1.]]]])

In [55]:
y=np.ones(6).reshape(2,1,3,1)
y

array([[[[1.],
         [1.],
         [1.]]],


       [[[1.],
         [1.],
         [1.]]]])

In [56]:
tf.add(x,y)

<tf.Tensor: shape=(2, 2, 3, 3), dtype=float64, numpy=
array([[[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]],


       [[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]]])>