<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/tf.math_module_divide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tf.divide**

In [1]:
import tensorflow as tf
import numpy as np


# **tf.divide with scaler tensor**

In [2]:
a=20
b=10
tf.divide(a,b)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

# **divide 2 list/tuple**

In [3]:
l1=[1,2,3,5]
l2=[2,3,4,5]
tf.divide(l2,l1)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2.        , 1.5       , 1.33333333, 1.        ])>

In [4]:
t1=(1,2,3,4)
t2=(4,3,2,2)
tf.divide(t1,t2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.25      , 0.66666667, 1.5       , 2.        ])>

# **divide list/tuple with scaler value**

In [5]:
l1=[12,21,39,24]
l2=[3]
tf.divide(l1,l2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 4.,  7., 13.,  8.])>

In [6]:
t1=(12,24,44,68)
t2=(4)
tf.divide(t1,t2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 3.,  6., 11., 17.])>

# divide constant tensor

In [7]:
con1=tf.constant([12,32,46])
con2=tf.constant([2,4,4])
tf.divide(con1,con2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 6. ,  8. , 11.5])>

In [8]:
con1=tf.constant([12,34,46])
con2=tf.constant([2])
tf.divide(con1,con2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 6., 17., 23.])>

# **divide tensor variable**

In [9]:
vr1=tf.Variable([12,34,48])
vr2=tf.Variable([2,4,4])
tf.divide(vr1,vr2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 6. ,  8.5, 12. ])>

In [10]:
vr1=tf.Variable([12,34,48])
vr2=tf.Variable([2])
tf.divide(vr1,vr2)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 6., 17., 24.])>