<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/tf.math_module_maximum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tf.maximum**

In [4]:
import tensorflow as tf
import numpy as np

# **Maximum of scaler**

In [3]:
a=10
b=10
tf.maximum(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

# **Maximum of List/Tuple**

In [5]:
l1=[1,3,4,5,6]
l2=[2,3,4,5,9]
tf.maximum(l1,l2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 9], dtype=int32)>

In [8]:
l1=[1,2,3,4]
l2=[9]
tf.maximum(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 9, 9, 9], dtype=int32)>

In [14]:
l1=[2,3,4]
a=12
tf.maximum(l1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 12, 12], dtype=int32)>

In [9]:
t1=(1,2,3,4)
t2=(5,6,7,8)
tf.maximum(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>

In [10]:
t1=(1,2,3,4)
t2=(5)
tf.maximum(t1,t2)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 5, 5, 5], dtype=int32)>

In [15]:
t1=(1,2,3,4)
a=12
tf.maximum(t1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([12, 12, 12, 12], dtype=int32)>

# **Maximum of numpy array**

In [11]:
npa1=np.array([1,2,3,4])
npa2=np.array([5,6,7,8])
tf.maximum(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([5, 6, 7, 8])>

In [12]:
npa1=np.array([1,2,3,4])
npa2=np.array([8])
tf.maximum(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([8, 8, 8, 8])>

In [13]:
npa1=np.array([1,2,3,4])
a=13
tf.maximum(npa1,a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([13, 13, 13, 13])>

# **Maximum of TF Constant**

In [16]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=tf.constant([5,6,7,8])
tf.maximum(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>

In [17]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=tf.constant([5])
tf.maximum(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 5, 5, 5], dtype=int32)>

In [18]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=9
tf.maximum(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 9, 9, 9], dtype=int32)>

# **Maximum of TF Constant**

In [19]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=tf.Variable([5,6,7,8])
tf.maximum(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>

In [20]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=tf.Variable([5])
tf.maximum(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 5, 5, 5], dtype=int32)>

In [21]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=13
tf.maximum(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([13, 13, 13, 13], dtype=int32)>