<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/tf.math_module_minimum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tf.maximum**

In [30]:
import tensorflow as tf
import numpy as np

# **Maximum of scaler**

In [31]:
a=10
b=10
tf.minimum(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

# **Maximum of List/Tuple**

In [32]:
l1=[1,3,4,5,6]
l2=[2,3,4,5,9]
tf.minimum(l1,l2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 4, 5, 6], dtype=int32)>

In [33]:
l1=[1,2,3,4]
l2=[9]
tf.minimum(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [34]:
l1=[2,3,4]
a=12
tf.minimum(l1,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [35]:
t1=(1,2,3,4)
t2=(5,6,7,8)
tf.minimum(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [36]:
t1=(1,2,3,4)
t2=(5)
tf.minimum(t1,t2)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [37]:
t1=(1,2,3,4)
a=12
tf.minimum(t1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# **Maximum of numpy array**

In [38]:
npa1=np.array([1,2,3,4])
npa2=np.array([5,6,7,8])
tf.minimum(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [39]:
npa1=np.array([1,2,3,4])
npa2=np.array([8])
tf.minimum(npa1,npa2)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [40]:
npa1=np.array([1,2,3,4])
a=13
tf.minimum(npa1,a)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

# **Maximum of TF Constant**

In [41]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=tf.constant([5,6,7,8])
tf.minimum(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [42]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=tf.constant([5])
tf.minimum(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [43]:
tf_ct1=tf.constant([1,2,3,4])
tf_ct2=9
tf.minimum(tf_ct1,tf_ct2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# **Maximum of TF Constant**

In [44]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=tf.Variable([5,6,7,8])
tf.minimum(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [45]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=tf.Variable([5])
tf.minimum(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [46]:
tf_vr1=tf.Variable([1,2,3,4])
tf_vr2=13
tf.minimum(tf_vr1,tf_vr2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>