<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf


In [5]:
b=tf.Variable(10)
b

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [6]:
a=tf.Variable([1,2,3,4,5])
a

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [13]:
string=tf.Variable(["kashish","jatin","manasvi","ashwin"])
string

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'kashish', b'jatin', b'manasvi', b'ashwin'], dtype=object)>

In [7]:
a.name

'Variable:0'

In [10]:
a.dtype

tf.int32

In [12]:
a.numpy()

array([1, 2, 3, 4, 5], dtype=int32)

In [14]:
tb=tf.Variable([3+4j])
tb

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

In [19]:
tb2=tf.constant([1,2,4,4,5])
tb2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 4, 4, 5], dtype=int32)>

In [20]:
tf.Variable(tb2)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 4, 4, 5], dtype=int32)>

In [28]:
con=tf.Variable([[1,2,3],[4,5,6]],shape=(2,3),dtype="float32")
con

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [30]:
tf.argmax(con).numpy()

array([1, 1, 1])

In [ ]:
a

In [31]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [32]:
a.assign([5,6,7,8,9])
a

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([5, 6, 7, 8, 9], dtype=int32)>

In [36]:
a.assign_add([5,6,7,8,9.0])
a

TypeError: Cannot convert [5, 6, 7, 8, 9.0] to EagerTensor of dtype int32