<a href="https://colab.research.google.com/github/Kashishkewat/tensorflow/blob/main/zeros_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **tf**.**zeros**()
creates a tensor with all elements set to zero

In [26]:
import tensorflow as tf

In [11]:
coon=tf.zeros((2,2),tf.int32)
coon

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [12]:
con3=tf.zeros((3,3,3),tf.float32)
con3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [13]:
con3.shape

TensorShape([3, 3, 3])

In [14]:
con3.dtype

tf.float32

In [15]:
con3.numpy()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

# **tf.zeros_like()**
creates a tensor with all elements set to zero


In [16]:
con_2d=tf.Variable((2,3,4),tf.float32)
con_2d

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [19]:
tf.zeros_like(con_2d)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 0], dtype=int32)>

In [20]:
con_d=tf.constant((1,2,3),dtype="float32")
con_d

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [21]:
tf.zeros_like(con_d)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

# **tf.zeros_initializer()**
initializer that generate tensors initialized to 0.


In [28]:
def zeros_initializer(shape,dtype,initializer):
  return tf.Variable(initializer(shape=shape,dtype=dtype))

In [30]:
zeros_initializer((2,2),tf.int32,tf.zeros_initializer())

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [32]:
zeros_initializer((2,2,2),tf.bool,tf.zeros_initializer())

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=bool, numpy=
array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])>

In [33]:
tf.Variable(tf.zeros_initializer()((2,2),tf.int32))


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>